### PR TITLE
Merge omegas

### PR DESCRIPTION
**Pull request by wreis**
Merge the functional fork from omega.

### CODE REVIEW

**Comment by wreis** [comment]
@bobtfish Could you please merge and do a new release? Oddly, the switch to ZMQ::FFI has been reverted on the last merge. Do you know why?

**Comment by wreis** [comment]
@ghenry I need comaint on M::P::ZeroMQ. it has failing tests currently on CPAN, and I have the fix ready on this PR. Thus, I will be happy to merge this and do a new release.

**Comment by ghenry** [comment]
Will do.

--
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 1224 279484
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie,
Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

Do you know we have our own VoIP provider called SureVoIP®? See
http://www.surevoip.co.uk

OpenPGP (GPG/PGP) Public Key: 0x8CFBA8E6 - Import from hkp://subkeys.pgp.net
or http://www.suretecgroup.com/0x8CFBA8E6.gpg

**Comment by bobtfish** [comment]
Has conflicts - can you fix so this will merge to master?

**Pull request merged**
